// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urfmbbbjkdwhpmujhucc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZm1iYmJqa2R3aHBtdWpodWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjg1NjgsImV4cCI6MjA2OTMwNDU2OH0.a08Cr3ab-3ORxcHU5S8nEogUHnxf_bMFKmDy4_HaP0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});